# Decision Tree

>参考：

>1、GBDT的python源码实现 

>2、Machine-Learning-From-Scratch 1的作者的github 

>3、Machine Learning From Scratch 1的作者参考的github 

>4、Machine learning algorithms 1的作者参考的github

  >[1]: https://zhuanlan.zhihu.com/p/32181306
  >[2]: https://github.com/RRdmlearning/Machine-Learning-From-Scratch
  >[3]: https://github.com/eriklindernoren/ML-From-Scratch
  >[4]: https://github.com/rushter/MLAlgorithms

 - 建立树节点类：二叉树节点，分割点、左右子节点、节点值

 - 建立决策树基类：因为不管回归树还是分类树，都是递归的建立树，根据一个标准找分割点，根据一个算法得到节点值

 - 建立分类树类：找分割点，用GINI系数或者熵；叶子节点，投票。和损失函数没有关系，可以做多分类，叶子节点的值是类别，不是数值
 
 - 建立回归树类：找分割点，分割前方差-（分割后左方差+分割后右方差），这个和损失函数选MSE时，相一致，这种分法，可以使loss降低。叶子节点的值，均值，也是和损失函数选MSE相一致，求导可知，均值可以使当前节点上样本loss最低。

Input X、y can be list or array, both ok.

## 1.Classification

In [1]:
from decision_tree_model import ClassificationTree
import numpy as np

In [8]:
X = np.array([[0, 0], [1, 1]])
Y = np.array([0, 1])
clf = ClassificationTree(max_depth=6)
clf.fit(X, Y)

In [9]:
clf.predict([[-1., 2.]])

[1]

In [10]:
clf.print_tree()

0:0? 
 T->0
 F->1


In [40]:
from sklearn.datasets import load_iris
iris = load_iris()
clf = ClassificationTree(max_depth=1)
clf.fit(iris.data, iris.target)

In [41]:
clf.print_tree()

2:3.0? 
 T->3:1.8? 
  T->2.0
  F->1.0
 F->0.0


In [45]:
clf.predict(iris.data[60:70])

[[5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]]


[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [46]:
iris.target[60:70]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 2.Regression

In [6]:
from decision_tree_model import RegressionTree

In [4]:
X = [[0, 0], [2, 2]]
y = [0.5, 2.5]
clf = RegressionTree()
clf.fit(X, y)
clf.predict([1, 1])

[2.5]

In [5]:
clf.print_tree()

0:0? 
 T->0.5
 F->2.5
