# Decision Tree

>参考：

>1、GBDT的python源码实现 
https://zhuanlan.zhihu.com/p/32181306

>2、Machine-Learning-From-Scratch 1的作者的github https://github.com/RRdmlearning/Machine-Learning-From-Scratch

>3、Machine Learning From Scratch 1的作者参考的github https://github.com/eriklindernoren/ML-From-Scratch

>4、Machine learning algorithms 1的作者参考的github https://github.com/rushter/MLAlgorithms

 - 建立树节点类：二叉树节点，分割点、左右子节点、节点值

 - 建立决策树基类：因为不管回归树还是分类树，都是递归的建立树，根据一个标准找分割点，根据一个算法得到节点值

 - 建立分类树类：找分割点，用GINI系数或者熵；叶子节点，投票。和损失函数没有关系，可以做多分类，叶子节点的值是类别，不是数值
 
 - 建立回归树类：找分割点，分割前方差-（分割后左方差+分割后右方差），这个和损失函数选MSE时，相一致，这种分法，可以使loss降低。叶子节点的值，均值，也是和损失函数选MSE相一致，求导可知，均值可以使当前节点上样本loss最低。

Input X、y can be list or array, both ok.

## 1.Classification

In [4]:
from decision_tree_model import ClassificationTree
import numpy as np

In [5]:
X = np.array([['黄', '长'], ['绿', '短']])
Y = np.array([0, 1])
clf = ClassificationTree(max_depth=6)
clf.fit(X, Y)

build current_depth: 0
-----------------
unique_values ['绿' '黄'] feature_i, 0
- - - - - - - 
threshold: 绿
Xy1: [['绿' '短' '1']] Xy2: [['黄' '长' '0']]
impurity 1.0
- - - - - - - 
threshold: 黄
Xy1: [['黄' '长' '0']] Xy2: [['绿' '短' '1']]
impurity 1.0
-----------------
unique_values ['短' '长'] feature_i, 1
- - - - - - - 
threshold: 短
Xy1: [['绿' '短' '1']] Xy2: [['黄' '长' '0']]
impurity 1.0
- - - - - - - 
threshold: 长
Xy1: [['黄' '长' '0']] Xy2: [['绿' '短' '1']]
impurity 1.0
build current_depth: 1
build current_depth: 1


In [6]:
clf.predict([['黄', '长']])

['0']

In [7]:
clf.print_tree()

0:绿? 
 T->1
 F->0


In [17]:
from sklearn.datasets import load_iris
iris = load_iris()
clf = ClassificationTree(max_depth=2)
clf.fit(iris.data, iris.target)

-----------------
unique_values [4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9] feature_i, 0
threshold: 4.3
threshold: 4.3  type: <class 'numpy.float64'>  isinstance(threshold, int) False  isinstance(threshold, float) True
Xy1: [[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1

threshold: 4.6  type: <class 'numpy.float64'>  isinstance(threshold, int) False  isinstance(threshold, float) True
Xy1: [[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.  

threshold: 2.4  type: <class 'numpy.float64'>  isinstance(threshold, int) False  isinstance(threshold, float) True
Xy1: [[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.4 

threshold: 2.1
threshold: 2.1  type: <class 'numpy.float64'>  isinstance(threshold, int) False  isinstance(threshold, float) True
Xy1: [[6.3 3.3 6.  2.5 2. ]
 [7.1 3.  5.9 2.1 2. ]
 [6.5 3.  5.8 2.2 2. ]
 [7.6 3.  6.6 2.1 2. ]
 [7.2 3.6 6.1 2.5 2. ]
 [6.8 3.  5.5 2.1 2. ]
 [5.8 2.8 5.1 2.4 2. ]
 [6.4 3.2 5.3 2.3 2. ]
 [7.7 3.8 6.7 2.2 2. ]
 [7.7 2.6 6.9 2.3 2. ]
 [6.9 3.2 5.7 2.3 2. ]
 [6.7 3.3 5.7 2.1 2. ]
 [6.4 2.8 5.6 2.1 2. ]
 [6.4 2.8 5.6 2.2 2. ]
 [7.7 3.  6.1 2.3 2. ]
 [6.3 3.4 5.6 2.4 2. ]
 [6.9 3.1 5.4 2.1 2. ]
 [6.7 3.1 5.6 2.4 2. ]
 [6.9 3.1 5.1 2.3 2. ]
 [6.8 3.2 5.9 2.3 2. ]
 [6.7 3.3 5.7 2.5 2. ]
 [6.7 3.  5.2 2.3 2. ]
 [6.2 3.4 5.4 2.3 2. ]] Xy2: [[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.

Xy1: [[6.3 3.3 6.  2.5 2. ]
 [7.1 3.  5.9 2.1 2. ]
 [6.3 2.9 5.6 1.8 2. ]
 [6.5 3.  5.8 2.2 2. ]
 [7.6 3.  6.6 2.1 2. ]
 [7.3 2.9 6.3 1.8 2. ]
 [6.7 2.5 5.8 1.8 2. ]
 [7.2 3.6 6.1 2.5 2. ]
 [7.7 3.8 6.7 2.2 2. ]
 [7.7 2.6 6.9 2.3 2. ]
 [6.9 3.2 5.7 2.3 2. ]
 [7.7 2.8 6.7 2.  2. ]
 [6.7 3.3 5.7 2.1 2. ]
 [7.2 3.2 6.  1.8 2. ]
 [6.4 2.8 5.6 2.1 2. ]
 [7.2 3.  5.8 1.6 2. ]
 [7.4 2.8 6.1 1.9 2. ]
 [7.9 3.8 6.4 2.  2. ]
 [6.4 2.8 5.6 2.2 2. ]
 [6.1 2.6 5.6 1.4 2. ]
 [7.7 3.  6.1 2.3 2. ]
 [6.3 3.4 5.6 2.4 2. ]
 [6.7 3.1 5.6 2.4 2. ]
 [6.8 3.2 5.9 2.3 2. ]
 [6.7 3.3 5.7 2.5 2. ]] Xy2: [[7.  3.2 4.7 1.4 1. ]
 [6.4 3.2 4.5 1.5 1. ]
 [6.9 3.1 4.9 1.5 1. ]
 [5.5 2.3 4.  1.3 1. ]
 [6.5 2.8 4.6 1.5 1. ]
 [5.7 2.8 4.5 1.3 1. ]
 [6.3 3.3 4.7 1.6 1. ]
 [4.9 2.4 3.3 1.  1. ]
 [6.6 2.9 4.6 1.3 1. ]
 [5.2 2.7 3.9 1.4 1. ]
 [5.  2.  3.5 1.  1. ]
 [5.9 3.  4.2 1.5 1. ]
 [6.  2.2 4.  1.  1. ]
 [6.1 2.9 4.7 1.4 1. ]
 [5.6 2.9 3.6 1.3 1. ]
 [6.7 3.1 4.4 1.4 1. ]
 [5.6 3.  4.5 1.5 1. ]
 [5.8 2.7 4.1 1.  1. ]


threshold: 5.7
threshold: 5.7  type: <class 'numpy.float64'>  isinstance(threshold, int) False  isinstance(threshold, float) True
Xy1: [[7.  3.2 4.7 1.4 1. ]
 [6.4 3.2 4.5 1.5 1. ]
 [6.9 3.1 4.9 1.5 1. ]
 [6.5 2.8 4.6 1.5 1. ]
 [5.7 2.8 4.5 1.3 1. ]
 [6.3 3.3 4.7 1.6 1. ]
 [6.6 2.9 4.6 1.3 1. ]
 [5.9 3.  4.2 1.5 1. ]
 [6.  2.2 4.  1.  1. ]
 [6.1 2.9 4.7 1.4 1. ]
 [6.7 3.1 4.4 1.4 1. ]
 [5.8 2.7 4.1 1.  1. ]
 [6.2 2.2 4.5 1.5 1. ]
 [6.1 2.8 4.  1.3 1. ]
 [6.3 2.5 4.9 1.5 1. ]
 [6.1 2.8 4.7 1.2 1. ]
 [6.4 2.9 4.3 1.3 1. ]
 [6.6 3.  4.4 1.4 1. ]
 [6.8 2.8 4.8 1.4 1. ]
 [6.7 3.  5.  1.7 1. ]
 [6.  2.9 4.5 1.5 1. ]
 [5.7 2.6 3.5 1.  1. ]
 [5.8 2.7 3.9 1.2 1. ]
 [6.  2.7 5.1 1.6 1. ]
 [6.  3.4 4.5 1.6 1. ]
 [6.7 3.1 4.7 1.5 1. ]
 [6.3 2.3 4.4 1.3 1. ]
 [6.1 3.  4.6 1.4 1. ]
 [5.8 2.6 4.  1.2 1. ]
 [5.7 3.  4.2 1.2 1. ]
 [5.7 2.9 4.2 1.3 1. ]
 [6.2 2.9 4.3 1.3 1. ]
 [5.7 2.8 4.1 1.3 1. ]
 [6.  2.2 5.  1.5 2. ]
 [7.2 3.  5.8 1.6 2. ]
 [6.3 2.8 5.1 1.5 2. ]
 [6.1 2.6 5.6 1.4 2. ]] Xy2: [[5.5 2.

In [18]:
clf.print_tree()

2:3.0? 
 T->3:1.8? 
  T->2:4.9? 
    T->2.0
    F->2.0
  F->2:5.0? 
    T->2.0
    F->1.0
 F->0.0


In [7]:
clf.predict(iris.data[60:70])

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [8]:
iris.target[60:70]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 2.Regression

In [1]:
from decision_tree_model import RegressionTree

In [2]:
X = [[0, 0], [1, 2], [-1,3]]
y = [8, 2.5, 7]
clf = RegressionTree()
clf.fit(X, y)
clf.predict([1, 1])

build current_depth: 0
-----------------
unique_values [-1  0  1] feature_i, 0
- - - - - - - 
threshold: -1
Xy1: [[ 0.   0.   8. ]
 [ 1.   2.   2.5]
 [-1.   3.   7. ]] Xy2: []
- - - - - - - 
threshold: 0
Xy1: [[0.  0.  8. ]
 [1.  2.  2.5]] Xy2: [[-1.  3.  7.]]
impurity 0.6805555555555554
- - - - - - - 
threshold: 1
Xy1: [[1.  2.  2.5]] Xy2: [[ 0.  0.  8.]
 [-1.  3.  7.]]
impurity 5.5555555555555545
-----------------
unique_values [0 2 3] feature_i, 1
- - - - - - - 
threshold: 0
Xy1: [[ 0.   0.   8. ]
 [ 1.   2.   2.5]
 [-1.   3.   7. ]] Xy2: []
- - - - - - - 
threshold: 2
Xy1: [[ 1.   2.   2.5]
 [-1.   3.   7. ]] Xy2: [[0. 0. 8.]]
impurity 2.3472222222222214
- - - - - - - 
threshold: 3
Xy1: [[-1.  3.  7.]] Xy2: [[0.  0.  8. ]
 [1.  2.  2.5]]
impurity 0.6805555555555554
build current_depth: 1
build current_depth: 1
-----------------
unique_values [-1.  0.] feature_i, 0
- - - - - - - 
threshold: -1.0
Xy1: [[ 0.  0.  8.]
 [-1.  3.  7.]] Xy2: []
- - - - - - - 
threshold: 0.0
Xy1: [[0. 0. 8

[2.5]

In [3]:
clf.print_tree()

0:1? 
 T->2.5
 F->0:0.0? 
  T->8.0
  F->7.0
